const toucansData = [
  {
    id: 1,
    name: "Toucan #01 — Violet Beanie",
    file: "images/Padfgetkhi.png",
    rarityRank: 3,
    tier: "Legendary",
    background: "Neon Lime",
    bgHex: "#7cd354",
    headwear: "Purple Beanie",
    outwear: "Puffer Jacket",
    beak: "Emerald Orange",
    eyes: "Cyan Glow",
    score: 98.4,
    description: "Master of the high canopy beat. Always stays cozy in cold cyber-breezes."
  },
  {
    id: 2,
    name: "Toucan #02 — Propeller Ace",
    file: "images/ttttkhi.png",
    rarityRank: 1,
    tier: "Mythic",
    background: "Tropical Green",
    bgHex: "#7cd354",
    headwear: "Propeller Cap",
    outwear: "Sky Blue Windbreaker",
    beak: "Emerald Orange",
    eyes: "Radar Target",
    score: 99.8,
    description: "Equipped with a spinning rotor cap to outmaneuver drone hawks in the metaverse."
  },
  {
    id: 3,
    name: "Toucan #03 — Crimson Hood",
    file: "images/Padrtfgetkhi.png",
    rarityRank: 5,
    tier: "Epic",
    background: "Jade Green",
    bgHex: "#7cd354",
    headwear: "Red Hoodie",
    outwear: "Crimson Tracksuit",
    beak: "Sunburst Gradient",
    eyes: "Emerald Rings",
    score: 94.2,
    description: "A street-smart bird on a mission to safeguard the canopy secrets."
  },
  {
    id: 4,
    name: "Toucan #04 — Neon Wanderer",
    file: "images/Padrtftrtgetkhi.png",
    rarityRank: 8,
    tier: "Rare",
    background: "Fresh Leaf",
    bgHex: "#7cd354",
    headwear: "Cobalt Beanie",
    outwear: "Midnight Parka",
    beak: "Tangerine Wave",
    eyes: "Deep Ocean",
    score: 89.5,
    description: "Roams distant pixel sanctuaries collecting vintage seeds and lost memory cards."
  },
  {
    id: 5,
    name: "Toucan #05 — Golden Beak",
    file: "images/Paeetkhi.png",
    rarityRank: 2,
    tier: "Legendary",
    background: "Bright Emerald",
    bgHex: "#7cd354",
    headwear: "Golden Feather",
    outwear: "Royal Robe",
    beak: "Golden Horizon",
    eyes: "Starlight Blue",
    score: 97.9,
    description: "Revered elder bird whose chirps recalibrate the smart contracts of the jungle."
  },
  {
    id: 6,
    name: "Toucan #06 — Cyber Puffer",
    file: "images/Pagfhfghgkhi.png",
    rarityRank: 7,
    tier: "Epic",
    background: "Vibrant Lime",
    bgHex: "#7cd354",
    headwear: "Violet Beanie",
    outwear: "Aqua Puffer",
    beak: "Sunset Orange",
    eyes: "Pixel Cyan",
    score: 91.0,
    description: "Never leaves home without high-capacity thermal plumage."
  },
  {
    id: 7,
    name: "Toucan #07 — Shadow Aviator",
    file: "images/Pakghghi.png",
    rarityRank: 4,
    tier: "Epic",
    background: "Neon Lime",
    bgHex: "#7cd354",
    headwear: "Stealth Cap",
    outwear: "Obsidian Jacket",
    beak: "Fire Gradient",
    eyes: "Prism Emerald",
    score: 95.7,
    description: "Glides unnoticed through dark clouds delivering encrypted messages to the Flock."
  },
  {
    id: 8,
    name: "Toucan #08 — Emerald Ranger",
    file: "images/dffghgetkhi.png",
    rarityRank: 10,
    tier: "Rare",
    background: "Classic Green",
    bgHex: "#7cd354",
    headwear: "Ranger Beret",
    outwear: "Forest Vest",
    beak: "Tropical Tri-tone",
    eyes: "Sky Sapphire",
    score: 85.3,
    description: "Protector of the ancient pixelized flora along the cyber-river."
  },
  {
    id: 9,
    name: "Toucan #09 — Prism Beak",
    file: "images/dfgfghgetkhi.png",
    rarityRank: 6,
    tier: "Epic",
    background: "Lime Spark",
    bgHex: "#7cd354",
    headwear: "Cyan Bandana",
    outwear: "Solar Coat",
    beak: "Prism Rainbow",
    eyes: "Amber Flare",
    score: 92.8,
    description: "Reflects solar pulses through its beak to light up dark rain-forest sectors."
  },
  {
    id: 10,
    name: "Toucan #10 — Chill Wave",
    file: "images/dfghgetkhi.png",
    rarityRank: 12,
    tier: "Uncommon",
    background: "Meadow Green",
    bgHex: "#7cd354",
    headwear: "Sun Cap",
    outwear: "Teal Fleece",
    beak: "Classic Orange",
    eyes: "Electric Lime",
    score: 81.6,
    description: "Basking in low-frequency synth beats near the digital waterfalls."
  },
  {
    id: 11,
    name: "Toucan #11 — Sunset Flier",
    file: "images/fghhgetkhi.png",
    rarityRank: 11,
    tier: "Uncommon",
    background: "Bright Lime",
    bgHex: "#7cd354",
    headwear: "Knit Cap",
    outwear: "Coral Anorak",
    beak: "Flame Gradient",
    eyes: "Deep Sky",
    score: 83.1,
    description: "Known to soar into dusk clouds searching for new blockchain heights."
  },
  {
    id: 12,
    name: "Toucan #12 — Midnight Scout",
    file: "images/fghhhgetkhi.png",
    rarityRank: 9,
    tier: "Rare",
    background: "Neon Green",
    bgHex: "#7cd354",
    headwear: "Night Visor",
    outwear: "Indigo Shell",
    beak: "Tropical Orange",
    eyes: "Laser Cyan",
    score: 88.0,
    description: "Scouts the night sky with high precision visual optics."
  },
  {
    id: 13,
    name: "Toucan #13 — Storm Feather",
    file: "images/sdfgfghgetkhi.png",
    rarityRank: 13,
    tier: "Common",
    background: "Jungle Green",
    bgHex: "#7cd354",
    headwear: "Storm Hoodie",
    outwear: "Wind Guard",
    beak: "Emerald Orange",
    eyes: "Sea Blue",
    score: 79.4,
    description: "Resilient flyer capable of navigating digital hurricanes effortlessly."
  },
  {
    id: 14,
    name: "Toucan #14 — Pixel Pioneer",
    file: "images/tttkhi - Copy.png",
    rarityRank: 14,
    tier: "Common",
    background: "Pure Green",
    bgHex: "#7cd354",
    headwear: "Pioneer Cap",
    outwear: "Basic Canvas",
    beak: "Standard Tri-tone",
    eyes: "Ocean Blue",
    score: 76.8,
    description: "One of the foundational avatars of the Toucanshood lineage."
  }
];

if (typeof module !== 'undefined') {
  module.exports = toucansData;
}
